// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_caculator_nguyennamphuong/test/history_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i10;

import 'package:flutter_caculator_nguyennamphuong/models/angle_mode.dart'
    as _i7;
import 'package:flutter_caculator_nguyennamphuong/models/calculator_mode.dart'
    as _i6;
import 'package:flutter_caculator_nguyennamphuong/providers/calculator_provider.dart'
    as _i5;
import 'package:flutter_caculator_nguyennamphuong/providers/history_provider.dart'
    as _i8;
import 'package:flutter_caculator_nguyennamphuong/providers/settings_provider.dart'
    as _i9;
import 'package:flutter_caculator_nguyennamphuong/services/storage_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveTheme(String? themeName) =>
      (super.noSuchMethod(
            Invocation.method(#saveTheme, [themeName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> loadTheme() =>
      (super.noSuchMethod(
            Invocation.method(#loadTheme, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#loadTheme, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveHistory(List<String>? historyJsonList) =>
      (super.noSuchMethod(
            Invocation.method(#saveHistory, [historyJsonList]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> loadHistory() =>
      (super.noSuchMethod(
            Invocation.method(#loadHistory, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> saveMemoryValue(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveMemoryValue, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double> loadMemoryValue() =>
      (super.noSuchMethod(
            Invocation.method(#loadMemoryValue, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveSettings(String? settingsJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settingsJson]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [CalculatorProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculatorProvider extends _i1.Mock
    implements _i5.CalculatorProvider {
  MockCalculatorProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get expression =>
      (super.noSuchMethod(
            Invocation.getter(#expression),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#expression),
            ),
          )
          as String);

  @override
  String get result =>
      (super.noSuchMethod(
            Invocation.getter(#result),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#result),
            ),
          )
          as String);

  @override
  _i6.CalculatorMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i6.CalculatorMode.basic,
          )
          as _i6.CalculatorMode);

  @override
  _i7.AngleMode get angleMode =>
      (super.noSuchMethod(
            Invocation.getter(#angleMode),
            returnValue: _i7.AngleMode.degrees,
          )
          as _i7.AngleMode);

  @override
  double get memory =>
      (super.noSuchMethod(Invocation.getter(#memory), returnValue: 0.0)
          as double);

  @override
  bool get hasMemory =>
      (super.noSuchMethod(Invocation.getter(#hasMemory), returnValue: false)
          as bool);

  @override
  bool get isResultCalculated =>
      (super.noSuchMethod(
            Invocation.getter(#isResultCalculated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isRadMode =>
      (super.noSuchMethod(Invocation.getter(#isRadMode), returnValue: false)
          as bool);

  @override
  set historyProvider(_i8.HistoryProvider? value) => super.noSuchMethod(
    Invocation.setter(#historyProvider, value),
    returnValueForMissingStub: null,
  );

  @override
  set settingsProvider(_i9.SettingsProvider? value) => super.noSuchMethod(
    Invocation.setter(#settingsProvider, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setHistoryProvider(_i8.HistoryProvider? provider) => super.noSuchMethod(
    Invocation.method(#setHistoryProvider, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void setSettingsProvider(_i9.SettingsProvider? provider) =>
      super.noSuchMethod(
        Invocation.method(#setSettingsProvider, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  void buttonPressed(String? text) => super.noSuchMethod(
    Invocation.method(#buttonPressed, [text]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> calculate() =>
      (super.noSuchMethod(
            Invocation.method(#calculate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addToExpression(String? value) => super.noSuchMethod(
    Invocation.method(#addToExpression, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearEntry() => super.noSuchMethod(
    Invocation.method(#clearEntry, []),
    returnValueForMissingStub: null,
  );

  @override
  void deleteLastCharacter() => super.noSuchMethod(
    Invocation.method(#deleteLastCharacter, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMode(_i6.CalculatorMode? mode) => super.noSuchMethod(
    Invocation.method(#toggleMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void handleLongPressClear() => super.noSuchMethod(
    Invocation.method(#handleLongPressClear, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleAngleMode() => super.noSuchMethod(
    Invocation.method(#toggleAngleMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void memoryAdd() => super.noSuchMethod(
    Invocation.method(#memoryAdd, []),
    returnValueForMissingStub: null,
  );

  @override
  void memorySubtract() => super.noSuchMethod(
    Invocation.method(#memorySubtract, []),
    returnValueForMissingStub: null,
  );

  @override
  void memoryRecall() => super.noSuchMethod(
    Invocation.method(#memoryRecall, []),
    returnValueForMissingStub: null,
  );

  @override
  void memoryClear() => super.noSuchMethod(
    Invocation.method(#memoryClear, []),
    returnValueForMissingStub: null,
  );

  @override
  void reuseExpression(String? expression) => super.noSuchMethod(
    Invocation.method(#reuseExpression, [expression]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
